### ISSUE TITLE
Tidy data dataframes and statistical questions 

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/MCL-DSCI-011-programming-in-python#30]
- Please can you discuss options for 2 dataframes and 2 statistical questions where:
    -  A wide dataframe is considered tidy, and 
    - A long dataframe is considered tidy. 

This will be used in the beginning of exercise 5 of Module 3 on the [content site](https://mcl-dsci-511-programming-in-python.netlify.app/en/module3)

- This would stem into the exercise 16 that is available [here](https://mcl-dsci-511-programming-in-python.netlify.app/en/module3) 
    - What statistical question would be a good option so melting creates tidy data? ( or I can scratch the MC question)

**Comment by ttimbers** [comment]
OK, for a data set that is too long (and needs to be widened to be tidy) I suggest the `untidy::language_diversity` data set. The statistical question would be what factors are associated with language diversity (as measured by the number of languages spoken in a country)?  Here's a snippet of too long (this is how the data set comes in this R package):


Continent | Country | Measurement | Value
-- | -- | -- | --
Africa | Algeria | Langs | 18 
Africa | Angola | Langs | 42
Oceania | Australia | Langs | 234
... | ... | ... | ...
Africa | Algeria | Area | 2381741
Africa | Angola | Area | 1246700
Oceania | Australia | Area | 7713364
... | ... | ... | ...
Africa | Algeria | Population | 25660
Africa | Angola | Population | 10303
Oceania | Australia | Population | 17336
... | ... | ... | ...

Tidy would be:

Continent | Country | Langs | Area | Population | ... |
--|--|--|--|--|--
Africa | Algeria | 18 | 2381741 | 25660 | ... |
Africa | Angola | 42 | 1246700 | 10303 | ... |
Oceania | Australia | 234 | 7713364 | 17336 | ... |

**Comment by ttimbers** [comment]
For wide to long, I used the child mortality under 5 data set in 523. With it, our statistical question that we'd like to answer with this data set is: whether there a relationship between country and/or year on under-five child mortality?

It comes really wide:

<img width="947" alt="Screen Shot 2020-06-29 at 10 53 48 PM" src="https://user-images.githubusercontent.com/6865016/86088554-6eaf6480-ba5b-11ea-9f84-c96b51ae4ad9.png">

And this is tidy:

<img width="326" alt="Screen Shot 2020-06-29 at 10 55 29 PM" src="https://user-images.githubusercontent.com/6865016/86088686-a8806b00-ba5b-11ea-83fd-7429f469a3bc.png">

**Comment by ttimbers** [comment]
Another too-wide one could be the Madrid pollution data set:

<img width="940" alt="Screen Shot 2020-06-29 at 10 59 15 PM" src="https://user-images.githubusercontent.com/6865016/86088989-352b2900-ba5c-11ea-907e-c1e3a0db7dcd.png">

I think here we ask a question along the lines of what pollutant decreases most over time. And to plot that easily we need to get the data set to look something like this:

<img width="315" alt="Screen Shot 2020-06-29 at 11 00 37 PM" src="https://user-images.githubusercontent.com/6865016/86089093-6572c780-ba5c-11ea-8d3d-a840788f5c02.png">

(note here we also summarize the data to get the average, you might not want to do that, or give them the averages in the wide format)

data: https://www.kaggle.com/decide-soluciones/air-quality-madrid

**Comment by hfboyce** [comment]
@ttimbers I added the first 2 examples in exercise 5 available [here](https://mcl-dsci-511-programming-in-python.netlify.app/en/module3).
 Does this explain it sufficiently? I made it quite simple in my explanation but I didn't want to over complicate it.

**Comment by ttimbers** [comment]
Some feedback small:

- [ ] slide 3, change "We are used to seeing the cereal data in a wide format, where there is a column for each measurement." to "We are used to seeing the cereal data in a wide format, where there is a column for each measured variable (e.g., calories, protein, sugar)."

Some bigger picture feedback:

I don't really like calling a data frame "wide" or "long". I think it has to be referenced to something, like itself in another format and then I would call it wider or longer. I see what you are trying to do here, address the misconception that a longer representation of the data is not necessarily "tidy". Which is good, but I think too much emphasis here is being placed on labelling something as wide and long. Where instead the emphasis should be placed on calling something tidy or not (and perhaps identifying how it could be made tidy).
